# Generated by Django 5.0.4 on 2024-05-05 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('employee_id', models.CharField(max_length=1024)),
                ('email', models.TextField()),
                ('type', models.TextField()),
                ('amount', models.IntegerField()),
                ('description', models.TextField()),
                ('approver', models.TextField(default='')),
                ('approved', models.BooleanField(default=None, null=True)),
                ('message', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.CharField(max_length=1024)),
                ('category_type', models.TextField()),
                ('approval_type', models.TextField()),
                ('condition', models.TextField(null=True)),
                ('amount', models.IntegerField()),
                ('approvers', models.JSONField(blank=True, null=True)),
                ('alert_type', models.TextField()),
                ('alert_recipients', models.JSONField(blank=True, null=True)),
                ('content', models.CharField(max_length=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
