# Generated by Django 5.0.4 on 2024-04-28 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('employee_id', models.CharField(max_length=1024)),
                ('email', models.TextField()),
                ('type', models.TextField()),
                ('amount', models.IntegerField()),
                ('description', models.TextField()),
                ('approver', models.TextField(default='')),
                ('approved', models.BooleanField(default=False)),
                ('message', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
