# Generated by Django 5.0.4 on 2024-04-28 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='approved',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
